Q1: What are some examples of unary operations in matrices?
Answer: Examples of unary operations include:

Transpose: Flipping a matrix over its diagonal.
Trace: The sum of the diagonal elements of the matrix.
Determinant: A scalar value that represents certain properties of the matrix.

Q2: Check if matrix_A is a symmetric matrix.
Matrix:

In [4]:
import numpy as np

# Define the matrix
matrix_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Check if symmetric
is_symmetric = (matrix_A == matrix_A.T).all()
print("Matrix A:\n", matrix_A)
print("\nIs Matrix A symmetric?", is_symmetric)



Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Is Matrix A symmetric? False


Practice Problem 1: Create a 4×4 random matrix and check if it is symmetric.

In [5]:
# Create a 4x4 random matrix
random_matrix = np.random.randint(1, 10, (4, 4))

# Transpose and check symmetry
transpose_random = random_matrix.T
is_symmetric_random = (random_matrix == transpose_random).all()

print("Random Matrix:\n", random_matrix)
print("\nIs the random matrix symmetric?", is_symmetric_random)


Random Matrix:
 [[1 6 8 7]
 [9 6 3 1]
 [3 8 3 5]
 [3 7 7 4]]

Is the random matrix symmetric? False


Q3: What is the trace of the following matrix?

In [6]:
# Define the matrix
matrix_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the trace
trace_A = np.trace(matrix_A)
print("Matrix A:\n", matrix_A)
print("\nTrace of Matrix A:", trace_A)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Trace of Matrix A: 15


Practice Problem 2: Find the trace of a 5×5 identity matrix.

In [7]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Calculate the trace
trace_identity = np.trace(identity_matrix)
print("Identity Matrix:\n", identity_matrix)
print("\nTrace of 5x5 Identity Matrix:", trace_identity)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Trace of 5x5 Identity Matrix: 5.0


Practice Problem 3: Compute the determinant of the following 3×3 matrix using NumPy.

In [8]:
# Define the matrix
matrix_D = np.array([[2, 3, 1], [4, 5, 6], [7, 8, 9]])

# Calculate the determinant
det_D = np.linalg.det(matrix_D)
print("Matrix D:\n", matrix_D)
print("\nDeterminant of Matrix D:", det_D)


Matrix D:
 [[2 3 1]
 [4 5 6]
 [7 8 9]]

Determinant of Matrix D: 9.000000000000005


Practice Problem 4: Generate a random 3×3 matrix representing pixel intensities, and find its transpose and determinant.

In [9]:
# Generate a random 3x3 matrix
random_pixel_matrix = np.random.randint(0, 256, (3, 3))

# Find the transpose and determinant
pixel_transpose = random_pixel_matrix.T
pixel_determinant = np.linalg.det(random_pixel_matrix)

print("Random Pixel Intensity Matrix:\n", random_pixel_matrix)
print("\nTranspose of Pixel Matrix:\n", pixel_transpose)
print("\nDeterminant of Pixel Matrix:\n", pixel_determinant)


Random Pixel Intensity Matrix:
 [[133 122 143]
 [228 205  35]
 [127  32 133]]

Transpose of Pixel Matrix:
 [[133 228 127]
 [122 205  32]
 [143  35 133]]

Determinant of Pixel Matrix:
 -2359630.000000002


Practice Problem 5: Create a symmetric 3×3 matrix and verify its properties.

In [10]:
# Define a symmetric matrix
symmetric_matrix = np.array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])

# Check if symmetric
transpose_symmetric = symmetric_matrix.T
is_symmetric_verified = (symmetric_matrix == transpose_symmetric).all()

print("Symmetric Matrix:\n", symmetric_matrix)
print("\nIs the matrix symmetric?", is_symmetric_verified)


Symmetric Matrix:
 [[2 1 1]
 [1 2 1]
 [1 1 2]]

Is the matrix symmetric? True
